DROP DATABASE coselTask2;
CREATE DATABASE coselTask2;
USE coselTask2;


CREATE TABLE `Artists`(
    `ArtisId` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ArtistName` VARCHAR(255) NOT NULL
);

CREATE TABLE `Genre`(
    `GenreId` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Genre` VARCHAR(255) NOT NULL
);

CREATE TABLE Albums(
    `AlbumId` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `AlbumName` VARCHAR(255) NOT NULL,
    `ReleaseDate` DATE,
    `ArtisId` INT NOT NULL,
    `GenreId` INT NOT NULL,
    FOREIGN KEY(ArtisId) REFERENCES Artists(ArtisId),
    FOREIGN KEY(GenreId) REFERENCES Genres(GenreId)
);


