DROP DATABASE Cart;
CREATE DATABASE Cart;
USE Cart;

CREATE TABLE Shop(
    PriceID INT NOT NULL AUTO_INCREMENT,
    Price VARCHAR(255),
    PRIMARY KEY(PriceID)
);

INSERT INTO Shop(Price) VALUES(5);
INSERT INTO Shop(Price) VALUES(3);
INSERT INTO Shop(Price) VALUES(10);
INSERT INTO Shop(Price) VALUES(7);
INSERT INTO Shop(Price) VALUES(6);
INSERT INTO Shop(Price) VALUES(4);
INSERT INTO Shop(Price) VALUES(3);
INSERT INTO Shop(Price) VALUES(16);
INSERT INTO Shop(Price) VALUES(19);
INSERT INTO Shop(Price) VALUES(420);